### ISSUE TITLE
Vue SDK: usage example mistake: 'logout' utility

### ISSUE THREAD

**Issue by camslice** [descope/descope-js#810]
Usage example:
```
<button @click="logout">Logout</button>
```
Throws an error in the dev tools console:
```
Uncaught (in promise) Error: "token" must be string or undefined
```
Usage example should be updated as follows:
```
<button @click="logout()">Logout</button>
```
This passes `undefined` to `logout()`

**Comment by asafshen** [comment]
hey @camslice 

is it possible that the user is not logged in?

to debug this, do you see `DSR` in locale storage or on cookie?

**Comment by camslice** [comment]
hey @asafshen 

user is definitely logged in.  i can see the DSR In both local storage and in a cookie.

i think the issue is that the default parameter passed to a Vue `@click` directive is the event, which is an object.

this:
```
<button @click="logout">Logout</button>
```

is the same as this:
```
<button @click="logout($event)">Logout</button>
```

`logout` is expecting a `string` or `undefined`

cam

**Comment by camslice** [comment]
@asafshen 🙏
